### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by NFuture**
Adding LICENSE file to patches directory

Adding missing LICENSE to the patches directory to address https://github.com/ZOSOpenTools/meta/issues/103

### CODE REVIEW

**Review by MikeFultonDev — APPROVED** [review]
LGTM - although since it's the same license for both, you could push the LICENSE file up to the patches directory and just have one.

**Comment by IgorTodorovskiIBM** [comment]
@NFuture are you able to place the license at the top level `patches/` directory. We currently generate a metadata.json file which assumes the LICENSE lives in the `patches/LICENSE` path

**Comment by NFuture** [comment]
Yeah. I'll make the change and push the same.

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Pull request merged**
